# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'quest_mainbyprxl.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QScrollArea, QSizePolicy, QSpacerItem, QStackedWidget,
    QTextBrowser, QTreeView, QVBoxLayout, QWidget)
import quest.resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1063, 626)
        MainWindow.setStyleSheet(u"")
        self.style_sheet = QWidget(MainWindow)
        self.style_sheet.setObjectName(u"style_sheet")
        self.style_sheet.setStyleSheet(u"")
        self.horizontalLayout_42 = QHBoxLayout(self.style_sheet)
        self.horizontalLayout_42.setSpacing(0)
        self.horizontalLayout_42.setObjectName(u"horizontalLayout_42")
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.menu = QFrame(self.style_sheet)
        self.menu.setObjectName(u"menu")
        self.menu.setStyleSheet(u"")
        self.menu.setFrameShape(QFrame.NoFrame)
        self.menu.setFrameShadow(QFrame.Raised)
        self.menu.setLineWidth(0)
        self.verticalLayout = QVBoxLayout(self.menu)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.top_logo_button = QPushButton(self.menu)
        self.top_logo_button.setObjectName(u"top_logo_button")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_logo_button.sizePolicy().hasHeightForWidth())
        self.top_logo_button.setSizePolicy(sizePolicy)
        self.top_logo_button.setMinimumSize(QSize(48, 46))
        self.top_logo_button.setSizeIncrement(QSize(0, 0))
        self.top_logo_button.setStyleSheet(u"QPushButton:hover{border: none;}")
        icon = QIcon()
        icon.addFile(u":/logos/images/logo/Quest_Q_RGB.png", QSize(), QIcon.Normal, QIcon.Off)
        self.top_logo_button.setIcon(icon)
        self.top_logo_button.setIconSize(QSize(36, 36))
        self.top_logo_button.setCheckable(False)
        self.top_logo_button.setFlat(True)

        self.verticalLayout.addWidget(self.top_logo_button)

        self.bottom_left_frame = QFrame(self.menu)
        self.bottom_left_frame.setObjectName(u"bottom_left_frame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.bottom_left_frame.sizePolicy().hasHeightForWidth())
        self.bottom_left_frame.setSizePolicy(sizePolicy1)
        self.bottom_left_frame.setMinimumSize(QSize(48, 0))
        self.bottom_left_frame.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.bottom_left_frame.setStyleSheet(u"")
        self.verticalLayout_4 = QVBoxLayout(self.bottom_left_frame)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.top_menu_bar = QFrame(self.bottom_left_frame)
        self.top_menu_bar.setObjectName(u"top_menu_bar")
        sizePolicy1.setHeightForWidth(self.top_menu_bar.sizePolicy().hasHeightForWidth())
        self.top_menu_bar.setSizePolicy(sizePolicy1)
        self.top_menu_bar.setMinimumSize(QSize(48, 0))
        self.top_menu_bar.setStyleSheet(u"")
        self.top_menu_bar.setFrameShape(QFrame.NoFrame)
        self.top_menu_bar.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.top_menu_bar)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.home_button = QPushButton(self.top_menu_bar)
        self.home_button.setObjectName(u"home_button")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.home_button.sizePolicy().hasHeightForWidth())
        self.home_button.setSizePolicy(sizePolicy2)
        self.home_button.setMinimumSize(QSize(48, 48))
        self.home_button.setAutoFillBackground(False)
        self.home_button.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u":/svgs/images/svgs/home_FILL0_wght200_GRAD0_opsz48.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.home_button.setIcon(icon1)
        self.home_button.setIconSize(QSize(32, 32))
        self.home_button.setCheckable(True)
        self.home_button.setChecked(True)
        self.home_button.setAutoExclusive(True)
        self.home_button.setFlat(True)

        self.verticalLayout_2.addWidget(self.home_button)

        self.workspace_button = QPushButton(self.top_menu_bar)
        self.workspace_button.setObjectName(u"workspace_button")
        sizePolicy2.setHeightForWidth(self.workspace_button.sizePolicy().hasHeightForWidth())
        self.workspace_button.setSizePolicy(sizePolicy2)
        self.workspace_button.setMinimumSize(QSize(48, 48))
        self.workspace_button.setStyleSheet(u"")
        icon2 = QIcon()
        icon2.addFile(u":/icon/images/icons/hub_FILL0_wght200_GRAD0_opsz48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.workspace_button.setIcon(icon2)
        self.workspace_button.setIconSize(QSize(32, 32))
        self.workspace_button.setCheckable(True)
        self.workspace_button.setAutoExclusive(True)
        self.workspace_button.setAutoRepeatInterval(100)
        self.workspace_button.setFlat(True)

        self.verticalLayout_2.addWidget(self.workspace_button)

        self.chat_button = QPushButton(self.top_menu_bar)
        self.chat_button.setObjectName(u"chat_button")
        self.chat_button.setStyleSheet(u"")
        icon3 = QIcon()
        icon3.addFile(u":/icon/images/icons/insert_chart_FILL0_wght200_GRAD0_opsz48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.chat_button.setIcon(icon3)
        self.chat_button.setIconSize(QSize(32, 48))
        self.chat_button.setCheckable(True)
        self.chat_button.setAutoExclusive(True)
        self.chat_button.setFlat(True)

        self.verticalLayout_2.addWidget(self.chat_button)

        self.setting_button = QPushButton(self.top_menu_bar)
        self.setting_button.setObjectName(u"setting_button")
        sizePolicy2.setHeightForWidth(self.setting_button.sizePolicy().hasHeightForWidth())
        self.setting_button.setSizePolicy(sizePolicy2)
        self.setting_button.setMinimumSize(QSize(48, 48))
        self.setting_button.setStyleSheet(u"")
        icon4 = QIcon()
        icon4.addFile(u":/icon/images/icons/settings_FILL0_wght200_GRAD0_opsz48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.setting_button.setIcon(icon4)
        self.setting_button.setIconSize(QSize(32, 32))
        self.setting_button.setCheckable(True)
        self.setting_button.setAutoExclusive(True)
        self.setting_button.setFlat(True)

        self.verticalLayout_2.addWidget(self.setting_button)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer)

        self.about = QPushButton(self.top_menu_bar)
        self.about.setObjectName(u"about")
        sizePolicy2.setHeightForWidth(self.about.sizePolicy().hasHeightForWidth())
        self.about.setSizePolicy(sizePolicy2)
        self.about.setMinimumSize(QSize(48, 48))
        self.about.setStyleSheet(u"")
        icon5 = QIcon()
        icon5.addFile(u":/icon/images/icons/help_FILL0_wght200_GRAD0_opsz48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.about.setIcon(icon5)
        self.about.setIconSize(QSize(32, 32))
        self.about.setCheckable(True)
        self.about.setAutoExclusive(True)
        self.about.setFlat(True)

        self.verticalLayout_2.addWidget(self.about)


        self.verticalLayout_4.addWidget(self.top_menu_bar)


        self.verticalLayout.addWidget(self.bottom_left_frame)


        self.horizontalLayout_42.addWidget(self.menu)

        self.main = QFrame(self.style_sheet)
        self.main.setObjectName(u"main")
        self.main.setStyleSheet(u"")
        self.main.setFrameShape(QFrame.NoFrame)
        self.main.setFrameShadow(QFrame.Raised)
        self.main.setLineWidth(0)
        self.verticalLayout_18 = QVBoxLayout(self.main)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.top_central_frame = QFrame(self.main)
        self.top_central_frame.setObjectName(u"top_central_frame")
        sizePolicy2.setHeightForWidth(self.top_central_frame.sizePolicy().hasHeightForWidth())
        self.top_central_frame.setSizePolicy(sizePolicy2)
        self.top_central_frame.setMinimumSize(QSize(0, 48))
        self.top_central_frame.setStyleSheet(u"")
        self.top_central_frame.setFrameShape(QFrame.NoFrame)
        self.top_central_frame.setFrameShadow(QFrame.Plain)
        self.top_central_frame.setLineWidth(0)
        self.horizontalLayout_2 = QHBoxLayout(self.top_central_frame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.top_label = QLabel(self.top_central_frame)
        self.top_label.setObjectName(u"top_label")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.top_label.sizePolicy().hasHeightForWidth())
        self.top_label.setSizePolicy(sizePolicy3)
        self.top_label.setMinimumSize(QSize(0, 0))
        self.top_label.setStyleSheet(u"")

        self.horizontalLayout_2.addWidget(self.top_label)

        self.top_right_frame = QFrame(self.top_central_frame)
        self.top_right_frame.setObjectName(u"top_right_frame")
        sizePolicy.setHeightForWidth(self.top_right_frame.sizePolicy().hasHeightForWidth())
        self.top_right_frame.setSizePolicy(sizePolicy)
        self.top_right_frame.setMinimumSize(QSize(0, 48))
        self.top_right_frame.setStyleSheet(u"")
        self.top_right_frame.setFrameShape(QFrame.NoFrame)
        self.top_right_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.top_right_frame)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.min_resize_button = QPushButton(self.top_right_frame)
        self.min_resize_button.setObjectName(u"min_resize_button")
        sizePolicy.setHeightForWidth(self.min_resize_button.sizePolicy().hasHeightForWidth())
        self.min_resize_button.setSizePolicy(sizePolicy)
        self.min_resize_button.setMinimumSize(QSize(36, 36))
        self.min_resize_button.setStyleSheet(u"")
        icon6 = QIcon()
        icon6.addFile(u":/icon/images/icons/remove_FILL0_wght200_GRAD0_opsz24.png", QSize(), QIcon.Normal, QIcon.Off)
        self.min_resize_button.setIcon(icon6)
        self.min_resize_button.setIconSize(QSize(24, 24))
        self.min_resize_button.setFlat(True)

        self.horizontalLayout_4.addWidget(self.min_resize_button, 0, Qt.AlignHCenter)

        self.norm_resize_button = QPushButton(self.top_right_frame)
        self.norm_resize_button.setObjectName(u"norm_resize_button")
        sizePolicy.setHeightForWidth(self.norm_resize_button.sizePolicy().hasHeightForWidth())
        self.norm_resize_button.setSizePolicy(sizePolicy)
        self.norm_resize_button.setMinimumSize(QSize(36, 36))
        self.norm_resize_button.setStyleSheet(u"")
        icon7 = QIcon()
        icon7.addFile(u":/icon/images/icons/open_in_new_FILL0_wght200_GRAD0_opsz48.png", QSize(), QIcon.Normal, QIcon.Off)
        icon7.addFile(u":/icon/images/icons/apps_FILL0_wght700_GRAD-25_opsz20.png", QSize(), QIcon.Normal, QIcon.On)
        icon7.addFile(u":/icon/images/icons/check_box_outline_blank_FILL0_wght200_GRAD0_opsz24.png", QSize(), QIcon.Selected, QIcon.On)
        self.norm_resize_button.setIcon(icon7)
        self.norm_resize_button.setIconSize(QSize(24, 24))
        self.norm_resize_button.setCheckable(False)
        self.norm_resize_button.setChecked(False)
        self.norm_resize_button.setFlat(True)

        self.horizontalLayout_4.addWidget(self.norm_resize_button)

        self.max_resize_button = QPushButton(self.top_right_frame)
        self.max_resize_button.setObjectName(u"max_resize_button")
        sizePolicy.setHeightForWidth(self.max_resize_button.sizePolicy().hasHeightForWidth())
        self.max_resize_button.setSizePolicy(sizePolicy)
        self.max_resize_button.setMinimumSize(QSize(36, 36))
        self.max_resize_button.setStyleSheet(u"")
        icon8 = QIcon()
        icon8.addFile(u":/icon/images/icons/open_in_new_down_FILL0_wght200_GRAD0_opsz48.png", QSize(), QIcon.Normal, QIcon.Off)
        icon8.addFile(u":/icon/images/icons/open_in_new_down_FILL0_wght200_GRAD0_opsz48.png", QSize(), QIcon.Normal, QIcon.On)
        icon8.addFile(u":/icon/images/icons/check_box_outline_blank_FILL0_wght200_GRAD0_opsz24.png", QSize(), QIcon.Selected, QIcon.On)
        self.max_resize_button.setIcon(icon8)
        self.max_resize_button.setIconSize(QSize(24, 24))
        self.max_resize_button.setCheckable(False)
        self.max_resize_button.setChecked(False)
        self.max_resize_button.setFlat(True)

        self.horizontalLayout_4.addWidget(self.max_resize_button, 0, Qt.AlignRight)

        self.exit_app_button = QPushButton(self.top_right_frame)
        self.exit_app_button.setObjectName(u"exit_app_button")
        sizePolicy.setHeightForWidth(self.exit_app_button.sizePolicy().hasHeightForWidth())
        self.exit_app_button.setSizePolicy(sizePolicy)
        self.exit_app_button.setMinimumSize(QSize(36, 36))
        self.exit_app_button.setStyleSheet(u"")
        icon9 = QIcon()
        icon9.addFile(u":/icon/images/icons/close_FILL0_wght200_GRAD0_opsz24.png", QSize(), QIcon.Normal, QIcon.Off)
        self.exit_app_button.setIcon(icon9)
        self.exit_app_button.setIconSize(QSize(24, 24))
        self.exit_app_button.setFlat(True)

        self.horizontalLayout_4.addWidget(self.exit_app_button)


        self.horizontalLayout_2.addWidget(self.top_right_frame)


        self.verticalLayout_18.addWidget(self.top_central_frame)

        self.quest_about = QFrame(self.main)
        self.quest_about.setObjectName(u"quest_about")
        self.quest_about.setMinimumSize(QSize(0, 0))
        self.quest_about.setMaximumSize(QSize(16777215, 0))
        self.quest_about.setStyleSheet(u"")
        self.quest_about.setFrameShape(QFrame.NoFrame)
        self.quest_about.setFrameShadow(QFrame.Raised)
        self.quest_about.setLineWidth(0)
        self.verticalLayout_38 = QVBoxLayout(self.quest_about)
        self.verticalLayout_38.setSpacing(0)
        self.verticalLayout_38.setObjectName(u"verticalLayout_38")
        self.verticalLayout_38.setContentsMargins(0, 0, 9, 0)
        self.scrollArea_3 = QScrollArea(self.quest_about)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setStyleSheet(u"")
        self.scrollArea_3.setFrameShape(QFrame.NoFrame)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 989, 71))
        self.scrollAreaWidgetContents_3.setStyleSheet(u"")
        self.horizontalLayout_27 = QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName(u"horizontalLayout_27")
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.textBrowser_22 = QTextBrowser(self.scrollAreaWidgetContents_3)
        self.textBrowser_22.setObjectName(u"textBrowser_22")
        self.textBrowser_22.setStyleSheet(u"")

        self.horizontalLayout_27.addWidget(self.textBrowser_22)

        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)

        self.verticalLayout_38.addWidget(self.scrollArea_3)

        self.hide_quest = QPushButton(self.quest_about)
        self.hide_quest.setObjectName(u"hide_quest")
        self.hide_quest.setStyleSheet(u"")
        self.hide_quest.setIcon(icon6)
        self.hide_quest.setFlat(True)

        self.verticalLayout_38.addWidget(self.hide_quest, 0, Qt.AlignHCenter)


        self.verticalLayout_18.addWidget(self.quest_about)

        self.bottom_frame = QFrame(self.main)
        self.bottom_frame.setObjectName(u"bottom_frame")
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.bottom_frame.sizePolicy().hasHeightForWidth())
        self.bottom_frame.setSizePolicy(sizePolicy4)
        self.bottom_frame.setMinimumSize(QSize(0, 0))
        self.bottom_frame.setFrameShape(QFrame.NoFrame)
        self.bottom_frame.setFrameShadow(QFrame.Plain)
        self.bottom_frame.setLineWidth(0)
        self.horizontalLayout_5 = QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.bottom_right_frame = QFrame(self.bottom_frame)
        self.bottom_right_frame.setObjectName(u"bottom_right_frame")
        self.bottom_right_frame.setFrameShape(QFrame.NoFrame)
        self.bottom_right_frame.setFrameShadow(QFrame.Plain)
        self.bottom_right_frame.setLineWidth(0)
        self.verticalLayout_5 = QVBoxLayout(self.bottom_right_frame)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget = QStackedWidget(self.bottom_right_frame)
        self.stackedWidget.setObjectName(u"stackedWidget")
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet(u"")
        self.stackedWidget.setLineWidth(0)
        self.home_page = QWidget()
        self.home_page.setObjectName(u"home_page")
        self.verticalLayout_35 = QVBoxLayout(self.home_page)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName(u"verticalLayout_35")
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.home_page_layout = QVBoxLayout()
        self.home_page_layout.setSpacing(0)
        self.home_page_layout.setObjectName(u"home_page_layout")

        self.verticalLayout_35.addLayout(self.home_page_layout)

        self.stackedWidget.addWidget(self.home_page)
        self.chat_page = QWidget()
        self.chat_page.setObjectName(u"chat_page")
        self.verticalLayout_9 = QVBoxLayout(self.chat_page)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.chat_layout = QVBoxLayout()
        self.chat_layout.setSpacing(0)
        self.chat_layout.setObjectName(u"chat_layout")

        self.verticalLayout_9.addLayout(self.chat_layout)

        self.stackedWidget.addWidget(self.chat_page)
        self.about_page = QWidget()
        self.about_page.setObjectName(u"about_page")
        self.verticalLayout_37 = QVBoxLayout(self.about_page)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName(u"verticalLayout_37")
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.about_page_layout = QVBoxLayout()
        self.about_page_layout.setSpacing(0)
        self.about_page_layout.setObjectName(u"about_page_layout")

        self.verticalLayout_37.addLayout(self.about_page_layout)

        self.stackedWidget.addWidget(self.about_page)
        self.results_viewer = QWidget()
        self.results_viewer.setObjectName(u"results_viewer")
        self.verticalLayout_6 = QVBoxLayout(self.results_viewer)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.results_viewer_layout = QVBoxLayout()
        self.results_viewer_layout.setSpacing(0)
        self.results_viewer_layout.setObjectName(u"results_viewer_layout")

        self.verticalLayout_6.addLayout(self.results_viewer_layout)

        self.stackedWidget.addWidget(self.results_viewer)
        self.settings_page = QWidget()
        self.settings_page.setObjectName(u"settings_page")
        self.verticalLayout_3 = QVBoxLayout(self.settings_page)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.settings_page)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Plain)
        self.frame.setLineWidth(0)
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_4 = QFrame(self.frame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setFrameShape(QFrame.NoFrame)
        self.frame_4.setFrameShadow(QFrame.Plain)
        self.frame_4.setLineWidth(0)
        self.horizontalLayout_28 = QHBoxLayout(self.frame_4)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName(u"horizontalLayout_28")
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.settings_menu = QFrame(self.frame_4)
        self.settings_menu.setObjectName(u"settings_menu")
        self.settings_menu.setMinimumSize(QSize(200, 0))
        self.settings_menu.setLayoutDirection(Qt.LeftToRight)
        self.settings_menu.setStyleSheet(u"")
        self.settings_menu.setFrameShape(QFrame.NoFrame)
        self.settings_menu.setFrameShadow(QFrame.Plain)
        self.settings_menu.setLineWidth(0)
        self.verticalLayout_16 = QVBoxLayout(self.settings_menu)
        self.verticalLayout_16.setSpacing(15)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.settings_menu)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setStyleSheet(u"font: 16pt \"Segoe UI\";")

        self.verticalLayout_16.addWidget(self.label_3, 0, Qt.AlignHCenter)

        self.appearance_button = QPushButton(self.settings_menu)
        self.appearance_button.setObjectName(u"appearance_button")
        self.appearance_button.setMinimumSize(QSize(0, 0))
        self.appearance_button.setStyleSheet(u"")
        icon10 = QIcon()
        icon10.addFile(u":/icon/images/icons/preview_FILL0_wght200_GRAD0_opsz48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.appearance_button.setIcon(icon10)
        self.appearance_button.setIconSize(QSize(24, 24))
        self.appearance_button.setCheckable(True)
        self.appearance_button.setChecked(True)
        self.appearance_button.setAutoExclusive(True)
        self.appearance_button.setFlat(True)

        self.verticalLayout_16.addWidget(self.appearance_button, 0, Qt.AlignLeft)

        self.environments_button = QPushButton(self.settings_menu)
        self.environments_button.setObjectName(u"environments_button")
        self.environments_button.setStyleSheet(u"")
        icon11 = QIcon()
        icon11.addFile(u":/icon/images/icons/token_FILL0_wght200_GRAD0_opsz48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.environments_button.setIcon(icon11)
        self.environments_button.setIconSize(QSize(24, 24))
        self.environments_button.setCheckable(True)
        self.environments_button.setAutoExclusive(True)
        self.environments_button.setFlat(True)

        self.verticalLayout_16.addWidget(self.environments_button, 0, Qt.AlignLeft)

        self.api_keys_button = QPushButton(self.settings_menu)
        self.api_keys_button.setObjectName(u"api_keys_button")
        self.api_keys_button.setStyleSheet(u"")
        icon12 = QIcon()
        icon12.addFile(u":/icon/images/icons/key_FILL0_wght200_GRAD0_opsz48.png", QSize(), QIcon.Normal, QIcon.Off)
        self.api_keys_button.setIcon(icon12)
        self.api_keys_button.setIconSize(QSize(24, 24))
        self.api_keys_button.setCheckable(True)
        self.api_keys_button.setAutoExclusive(True)
        self.api_keys_button.setFlat(True)

        self.verticalLayout_16.addWidget(self.api_keys_button, 0, Qt.AlignLeft)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_16.addItem(self.verticalSpacer_2)


        self.horizontalLayout_28.addWidget(self.settings_menu)

        self.frame_3 = QFrame(self.frame_4)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.verticalLayout_19 = QVBoxLayout(self.frame_3)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget_3 = QStackedWidget(self.frame_3)
        self.stackedWidget_3.setObjectName(u"stackedWidget_3")
        self.appearance_page = QWidget()
        self.appearance_page.setObjectName(u"appearance_page")
        self.verticalLayout_20 = QVBoxLayout(self.appearance_page)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName(u"verticalLayout_20")
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.frame_5 = QFrame(self.appearance_page)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.NoFrame)
        self.frame_5.setFrameShadow(QFrame.Plain)
        self.frame_5.setLineWidth(0)
        self.verticalLayout_36 = QVBoxLayout(self.frame_5)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName(u"verticalLayout_36")
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.frame_12 = QFrame(self.frame_5)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setFrameShape(QFrame.NoFrame)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.frame_12.setLineWidth(0)
        self.horizontalLayout_32 = QHBoxLayout(self.frame_12)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName(u"horizontalLayout_32")
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.frame_11 = QFrame(self.frame_12)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setFrameShape(QFrame.NoFrame)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.frame_11.setLineWidth(0)
        self.horizontalLayout_30 = QHBoxLayout(self.frame_11)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName(u"horizontalLayout_30")
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)

        self.horizontalLayout_32.addWidget(self.frame_11)


        self.verticalLayout_36.addWidget(self.frame_12)

        self.frame_10 = QFrame(self.frame_5)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setFrameShape(QFrame.NoFrame)
        self.frame_10.setFrameShadow(QFrame.Plain)
        self.frame_10.setLineWidth(0)
        self.verticalLayout_8 = QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setSpacing(15)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 15, 0, 0)
        self.label = QLabel(self.frame_10)
        self.label.setObjectName(u"label")
        self.label.setStyleSheet(u"font: 26pt \"Segoe UI\";")

        self.verticalLayout_8.addWidget(self.label)

        self.light_mode_button = QPushButton(self.frame_10)
        self.light_mode_button.setObjectName(u"light_mode_button")
        self.light_mode_button.setCheckable(True)
        self.light_mode_button.setChecked(True)
        self.light_mode_button.setAutoExclusive(True)
        self.light_mode_button.setFlat(True)

        self.verticalLayout_8.addWidget(self.light_mode_button)

        self.dark_mode_button = QPushButton(self.frame_10)
        self.dark_mode_button.setObjectName(u"dark_mode_button")
        self.dark_mode_button.setCheckable(True)
        self.dark_mode_button.setAutoExclusive(True)
        self.dark_mode_button.setFlat(True)

        self.verticalLayout_8.addWidget(self.dark_mode_button)

        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_8.addItem(self.verticalSpacer_3)


        self.verticalLayout_36.addWidget(self.frame_10)


        self.verticalLayout_20.addWidget(self.frame_5)

        self.stackedWidget_3.addWidget(self.appearance_page)
        self.environments_page = QWidget()
        self.environments_page.setObjectName(u"environments_page")
        self.verticalLayout_34 = QVBoxLayout(self.environments_page)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName(u"verticalLayout_34")
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.frame_8 = QFrame(self.environments_page)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setFrameShape(QFrame.NoFrame)
        self.frame_8.setFrameShadow(QFrame.Plain)
        self.verticalLayout_12 = QVBoxLayout(self.frame_8)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.frame_9 = QFrame(self.frame_8)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setFrameShape(QFrame.NoFrame)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.verticalLayout_11 = QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.label_4 = QLabel(self.frame_9)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setStyleSheet(u"font: 26pt \"Segoe UI\";")
        self.label_4.setLineWidth(0)

        self.verticalLayout_11.addWidget(self.label_4)

        self.env_path = QLineEdit(self.frame_9)
        self.env_path.setObjectName(u"env_path")

        self.verticalLayout_11.addWidget(self.env_path)

        self.env_view = QTreeView(self.frame_9)
        self.env_view.setObjectName(u"env_view")

        self.verticalLayout_11.addWidget(self.env_view)


        self.verticalLayout_12.addWidget(self.frame_9)


        self.verticalLayout_34.addWidget(self.frame_8)

        self.stackedWidget_3.addWidget(self.environments_page)
        self.api_keys_page = QWidget()
        self.api_keys_page.setObjectName(u"api_keys_page")
        self.verticalLayout_32 = QVBoxLayout(self.api_keys_page)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName(u"verticalLayout_32")
        self.verticalLayout_32.setContentsMargins(0, 9, 0, 0)
        self.label_2 = QLabel(self.api_keys_page)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setStyleSheet(u"font: 26pt \"Segoe UI\";")

        self.verticalLayout_32.addWidget(self.label_2, 0, Qt.AlignTop)

        self.frame_6 = QFrame(self.api_keys_page)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setFrameShape(QFrame.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.verticalLayout_10 = QVBoxLayout(self.frame_6)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.api_entry = QLineEdit(self.frame_6)
        self.api_entry.setObjectName(u"api_entry")

        self.verticalLayout_10.addWidget(self.api_entry)

        self.frame_13 = QFrame(self.frame_6)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setFrameShape(QFrame.NoFrame)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_13)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2)

        self.save_api = QPushButton(self.frame_13)
        self.save_api.setObjectName(u"save_api")
        self.save_api.setStyleSheet(u"")
        icon13 = QIcon()
        icon13.addFile(u":/icon/images/icons/1outline_save_black_24dp.png", QSize(), QIcon.Normal, QIcon.Off)
        self.save_api.setIcon(icon13)
        self.save_api.setIconSize(QSize(32, 32))
        self.save_api.setFlat(True)

        self.horizontalLayout_3.addWidget(self.save_api)

        self.load_api = QPushButton(self.frame_13)
        self.load_api.setObjectName(u"load_api")
        self.load_api.setStyleSheet(u"")
        icon14 = QIcon()
        icon14.addFile(u":/icon/images/icons/send_FILL0_wght200_GRAD0_opsz48.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.load_api.setIcon(icon14)
        self.load_api.setIconSize(QSize(32, 32))
        self.load_api.setFlat(True)

        self.horizontalLayout_3.addWidget(self.load_api)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_3)


        self.verticalLayout_10.addWidget(self.frame_13)


        self.verticalLayout_32.addWidget(self.frame_6, 0, Qt.AlignTop)

        self.verticalSpacer_4 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_32.addItem(self.verticalSpacer_4)

        self.stackedWidget_3.addWidget(self.api_keys_page)
        self.ph1 = QWidget()
        self.ph1.setObjectName(u"ph1")
        self.verticalLayout_33 = QVBoxLayout(self.ph1)
        self.verticalLayout_33.setSpacing(0)
        self.verticalLayout_33.setObjectName(u"verticalLayout_33")
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.frame_7 = QFrame(self.ph1)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.NoFrame)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.label_7 = QLabel(self.frame_7)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(210, 230, 341, 21))

        self.verticalLayout_33.addWidget(self.frame_7)

        self.stackedWidget_3.addWidget(self.ph1)
        self.ph2 = QWidget()
        self.ph2.setObjectName(u"ph2")
        self.verticalLayout_21 = QVBoxLayout(self.ph2)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName(u"verticalLayout_21")
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.frame_2 = QFrame(self.ph2)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(200, 160, 121, 41))

        self.verticalLayout_21.addWidget(self.frame_2)

        self.stackedWidget_3.addWidget(self.ph2)

        self.verticalLayout_19.addWidget(self.stackedWidget_3)


        self.horizontalLayout_28.addWidget(self.frame_3)


        self.horizontalLayout.addWidget(self.frame_4)


        self.verticalLayout_3.addWidget(self.frame)

        self.stackedWidget.addWidget(self.settings_page)
        self.work_space = QWidget()
        self.work_space.setObjectName(u"work_space")
        self.verticalLayout_7 = QVBoxLayout(self.work_space)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.work_space_layout = QVBoxLayout()
        self.work_space_layout.setSpacing(0)
        self.work_space_layout.setObjectName(u"work_space_layout")

        self.verticalLayout_7.addLayout(self.work_space_layout)

        self.stackedWidget.addWidget(self.work_space)

        self.verticalLayout_5.addWidget(self.stackedWidget)


        self.horizontalLayout_5.addWidget(self.bottom_right_frame)


        self.verticalLayout_18.addWidget(self.bottom_frame)

        self.credit_frame = QFrame(self.main)
        self.credit_frame.setObjectName(u"credit_frame")
        sizePolicy3.setHeightForWidth(self.credit_frame.sizePolicy().hasHeightForWidth())
        self.credit_frame.setSizePolicy(sizePolicy3)
        self.credit_frame.setMinimumSize(QSize(0, 24))
        self.credit_frame.setStyleSheet(u"border: 0px;")
        self.credit_frame.setFrameShape(QFrame.NoFrame)
        self.credit_frame.setFrameShadow(QFrame.Plain)
        self.credit_frame.setLineWidth(0)
        self.horizontalLayout_6 = QHBoxLayout(self.credit_frame)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.credit_label = QLabel(self.credit_frame)
        self.credit_label.setObjectName(u"credit_label")
        self.credit_label.setStyleSheet(u"")
        self.credit_label.setLineWidth(0)

        self.horizontalLayout_6.addWidget(self.credit_label, 0, Qt.AlignLeft)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_6.addItem(self.horizontalSpacer)

        self.version = QFrame(self.credit_frame)
        self.version.setObjectName(u"version")
        self.version.setFrameShape(QFrame.NoFrame)
        self.version.setFrameShadow(QFrame.Raised)
        self.version.setLineWidth(0)
        self.horizontalLayout_8 = QHBoxLayout(self.version)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.version_label = QLabel(self.version)
        self.version_label.setObjectName(u"version_label")
        self.version_label.setStyleSheet(u"")
        self.version_label.setLineWidth(0)

        self.horizontalLayout_8.addWidget(self.version_label)


        self.horizontalLayout_6.addWidget(self.version, 0, Qt.AlignRight)


        self.verticalLayout_18.addWidget(self.credit_frame)


        self.horizontalLayout_42.addWidget(self.main)

        MainWindow.setCentralWidget(self.style_sheet)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(4)
        self.stackedWidget_3.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        self.top_logo_button.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Menu</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.top_logo_button.setText("")
#if QT_CONFIG(tooltip)
        self.home_button.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Home</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.home_button.setText("")
#if QT_CONFIG(tooltip)
        self.workspace_button.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Work space</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.workspace_button.setText("")
#if QT_CONFIG(tooltip)
        self.chat_button.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Data Visualization</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.chat_button.setText("")
#if QT_CONFIG(tooltip)
        self.setting_button.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Settings</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.setting_button.setText("")
#if QT_CONFIG(tooltip)
        self.about.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>About</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.about.setText("")
        self.top_label.setText(QCoreApplication.translate("MainWindow", u"QuESt 2.0 - Open-Source Python Platform for Energy Storage Analytics", None))
#if QT_CONFIG(tooltip)
        self.min_resize_button.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Minimize</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.min_resize_button.setText("")
#if QT_CONFIG(tooltip)
        self.norm_resize_button.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Restore Down</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.norm_resize_button.setText("")
#if QT_CONFIG(tooltip)
        self.max_resize_button.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Maximize</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.max_resize_button.setText("")
#if QT_CONFIG(tooltip)
        self.exit_app_button.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Close</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.exit_app_button.setText("")
        self.textBrowser_22.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">QuESt processes display is under construction.</span></p></body></html>", None))
        self.hide_quest.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.appearance_button.setText(QCoreApplication.translate("MainWindow", u"       Appearance             ", None))
        self.environments_button.setText(QCoreApplication.translate("MainWindow", u"      Environments           ", None))
        self.api_keys_button.setText(QCoreApplication.translate("MainWindow", u"          API Key               ", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Appearance", None))
        self.light_mode_button.setText(QCoreApplication.translate("MainWindow", u"Light Mode", None))
#if QT_CONFIG(tooltip)
        self.dark_mode_button.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.dark_mode_button.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Environments", None))
        self.env_path.setPlaceholderText(QCoreApplication.translate("MainWindow", u"path/to/envs...", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"API Key", None))
        self.api_entry.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter API Key...", None))
#if QT_CONFIG(tooltip)
        self.save_api.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Save</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.save_api.setText("")
#if QT_CONFIG(tooltip)
        self.load_api.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Load</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.load_api.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Place Holder 1", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"PlaceHolder 2", None))
        self.credit_label.setText(QCoreApplication.translate("MainWindow", u"Developed by Sandia National Laboratories", None))
        self.version_label.setText(QCoreApplication.translate("MainWindow", u"ver 2.0.b ", None))
    # retranslateUi

